### PR TITLE
update add_watch_data function

### PR DESCRIPTION
**Pull request by Sagarnandeshwar**
Loop (lines 90-93) to update the watch time for every previous occurrence movie. Resolving repetition of movies in user_store for 'watch' movies.

### CODE REVIEW

**Comment by sophearahsp** [comment]
Did you make the changes you mentioned in my PR here?
> Hey Sophearah, I was thinking of saving the model evaluation in JSON format instead of String (evaluation.py lines 150-152). it will be easier to use that data later then. I will implement it by tonight.

**Comment by wdrdg** [comment]
I remembered that the movie_store only stores the movie once even though it actually appears multiple times. Do we solve this problem?

**Comment by Sagarnandeshwar** [comment]
> Did you make the changes you mentioned in my PR here?
> 
> > Hey Sophearah, I was thinking of saving the model evaluation in JSON format instead of String (evaluation.py lines 150-152). it will be easier to use that data later then. I will implement it by tonight.

hey sorry I forgot to update it, I will do it here and in your repository.

**Comment by Sagarnandeshwar** [comment]
> I remembered that the movie_store only stores the movie once even though it actually appears multiple times. Do we solve this problem?

No. I added a loop that will only update(to the max time) the watch_time of the same movie in a different time_stamp, but do you want the movie to appear multiple times in the same time_stamp?

**Comment by wdrdg** [comment]
> 

I think with the max time is reasonable :)

**Comment by wdrdg** [comment]
> > I remembered that the movie_store only stores the movie once even though it actually appears multiple times. Do we solve this problem?
> 
> No. I added a loop that will only update(to the max time) the watch_time of the same movie in a different time_stamp, but do you want the movie to appear multiple times in the same time_stamp?
I think with the max time is reasonable :)

**Pull request merged**
